### ISSUE TITLE
Attach to multiple processes with the same name

### ISSUE THREAD

**Issue by mhtsbt** [fareloz/AttachToolbar#1]
I don't know if it is already possible, but it would be great if it would be possible to attach to all processes with the same name. For example I have multiple "dotnet.exe" processes, and I would like to be able to use one button to attach to all of these.

**Comment by fareloz** [comment]
Hello!
You are right, currently it is not possible to attach to several same-named processes.
But I think your request is reasonable to implement. I'll do it when I have free time.
Thank you for the feedback.

**Comment by fareloz** [comment]
Done

**Comment by mhtsbt** [comment]
hero!  🥇
