### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by irvnriir** [fareloz/AttachToolbar#2]
Would be good to add "debugger" to "extensions and updates"'s menu description for users wouldn't need to follow links to figure out what the package is about.

**Comment by fareloz** [comment]
@Ilias48rus Could you please provide some screenshots of the menu?  I'm not completely sure what the menu you're talking about

**Comment by irvnriir** [comment]
@fareloz (the menu with a list of packages to install them from, this package's description basically misses a "debugger" word)
