### ISSUE TITLE
Thanks for making this!

### ISSUE THREAD

**Issue by iainprior-diligent** [fareloz/AttachToolbar#3]
Just wanted to say thanks for the time and effort. Very useful!

**Comment by fareloz** [comment]
Thank you for the feedback! I am happy that my small tool is also handy for others.
Although the issues section is not dedicated for feedbacks, but the real issues with the code\functionality if the software. Also opened issues are registered on extension's page:
![image](https://user-images.githubusercontent.com/7237969/74821403-3446f580-530c-11ea-9fc3-502fe66aee75.png)
I would really love to have your feedback on "Rating & Review" page of the extension here: https://marketplace.visualstudio.com/items?itemName=fareloz.AttachToolbar&ssr=false#review-details
